version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: "--default-authentication-plugin=mysql_native_password"
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    image: backend
    networks:
      - backend-network
      - frontend-network
    secrets:
      - db-password

  frontend:
    image: frontend
    ports:
      - 80:80
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:
secrets:
  db-password:
    file: db/password.txt
